[package]
name = "libboxer"
version = "0.1.0"
authors = ["feenk gmbh <contact@feenk.com>"]
edition = "2021"

[lib]
name = "Boxer"
crate-type = ["cdylib"]

[dependencies]
array-box = "1.0"
geometry-box = "1.0"
string-box = "1.1"
value-box = "2.1"
crossbeam = "0.8"
phlow-core = { package = "phlow", version = "1.3", optional = true, features = [ "phlow-derive" ] }
phlow-extensions = { version = "1.3", optional = true }

[features]
phlow = [ "phlow-core", "phlow-extensions", "value-box/phlow" ]